<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ATAS.Indicators">
      <HintPath>C:\Program Files (x86)\ATAS Platform\ATAS.Indicators.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OFT.Rendering">
      <HintPath>C:\Program Files (x86)\ATAS Platform\OFT.Rendering.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ATAS.Types">
      <HintPath>C:\Program Files (x86)\ATAS Platform\ATAS.Types.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
